profiles:
  active: dev
#### application-dev.yml
server:
  port: 8001
mybatis-plus:
  configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper-locations: classpath:com/atguigu/service/*/mapper/*.xml
global-config:
  db-config:
  logic-delete-value: 1
logic-not-delete-value: 0
spring:
datasource:
  type: com.zaxxer.hikari.HikariDataSource
driver-class-name: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://ibacon-6.mysql.rds.aliyuncs.com:3306/guli?serverTimezone=GMT%2B8
username: ibacon
password: ibacon66
hikari:
  connection-test-query: SELECT 1
connection-timeout: 60000
idle-timeout: 500000
max-lifetime: 540000
maximum-pool-size: 12
minimum-idle: 10
pool-name: GuliHikariPool
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
time-zone: GMT+8